// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/product_catalog.proto

package productcatalogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	ProductCatalogService_GetProduct_FullMethodName       = "/product_catalog.ProductCatalogService/GetProduct"
	ProductCatalogService_GetSKU_FullMethodName           = "/product_catalog.ProductCatalogService/GetSKU"
	ProductCatalogService_GetSKUsByProduct_FullMethodName = "/product_catalog.ProductCatalogService/GetSKUsByProduct"
)

type ProductCatalogServiceClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
	GetSKU(ctx context.Context, in *GetSKURequest, opts ...grpc.CallOption) (*GetSKUResponse, error)
	GetSKUsByProduct(ctx context.Context, in *GetSKUsByProductRequest, opts ...grpc.CallOption) (*GetSKUsByProductResponse, error)
}

type productCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductCatalogServiceClient(cc grpc.ClientConnInterface) ProductCatalogServiceClient {
	return &productCatalogServiceClient{cc}
}

func (c *productCatalogServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductCatalogService_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCatalogServiceClient) GetSKU(ctx context.Context, in *GetSKURequest, opts ...grpc.CallOption) (*GetSKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSKUResponse)
	err := c.cc.Invoke(ctx, ProductCatalogService_GetSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCatalogServiceClient) GetSKUsByProduct(ctx context.Context, in *GetSKUsByProductRequest, opts ...grpc.CallOption) (*GetSKUsByProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSKUsByProductResponse)
	err := c.cc.Invoke(ctx, ProductCatalogService_GetSKUsByProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type ProductCatalogServiceServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	GetSKU(context.Context, *GetSKURequest) (*GetSKUResponse, error)
	GetSKUsByProduct(context.Context, *GetSKUsByProductRequest) (*GetSKUsByProductResponse, error)
	mustEmbedUnimplementedProductCatalogServiceServer()
}

type UnimplementedProductCatalogServiceServer struct{}

func (UnimplementedProductCatalogServiceServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductCatalogServiceServer) GetSKU(context.Context, *GetSKURequest) (*GetSKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSKU not implemented")
}
func (UnimplementedProductCatalogServiceServer) GetSKUsByProduct(context.Context, *GetSKUsByProductRequest) (*GetSKUsByProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSKUsByProduct not implemented")
}
func (UnimplementedProductCatalogServiceServer) mustEmbedUnimplementedProductCatalogServiceServer() {}
func (UnimplementedProductCatalogServiceServer) testEmbeddedByValue()                               {}

type UnsafeProductCatalogServiceServer interface {
	mustEmbedUnimplementedProductCatalogServiceServer()
}

func RegisterProductCatalogServiceServer(s grpc.ServiceRegistrar, srv ProductCatalogServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductCatalogService_ServiceDesc, srv)
}

func _ProductCatalogService_GetProduct_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCatalogServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: ProductCatalogService_GetProduct_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ProductCatalogServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCatalogService_GetSKU_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetSKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCatalogServiceServer).GetSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: ProductCatalogService_GetSKU_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ProductCatalogServiceServer).GetSKU(ctx, req.(*GetSKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCatalogService_GetSKUsByProduct_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetSKUsByProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCatalogServiceServer).GetSKUsByProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: ProductCatalogService_GetSKUsByProduct_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(ProductCatalogServiceServer).GetSKUsByProduct(ctx, req.(*GetSKUsByProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var ProductCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_catalog.ProductCatalogService",
	HandlerType: (*ProductCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetProduct", Handler: _ProductCatalogService_GetProduct_Handler},
		{MethodName: "GetSKU", Handler: _ProductCatalogService_GetSKU_Handler},
		{MethodName: "GetSKUsByProduct", Handler: _ProductCatalogService_GetSKUsByProduct_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product_catalog.proto",
}
