// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: currency.proto

package currencypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesRequest) Reset() {
	*x = ListCurrenciesRequest{}
	mi := &file_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesRequest) ProtoMessage() {}

func (x *ListCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

type CurrencyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag          string                 `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Decimals      int32                  `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyProto) Reset() {
	*x = CurrencyProto{}
	mi := &file_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyProto) ProtoMessage() {}

func (x *CurrencyProto) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyProto.ProtoReflect.Descriptor instead.
func (*CurrencyProto) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyProto) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CurrencyProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CurrencyProto) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *CurrencyProto) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CurrencyProto) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*CurrencyProto       `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesResponse) Reset() {
	*x = ListCurrenciesResponse{}
	mi := &file_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesResponse) ProtoMessage() {}

func (x *ListCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{2}
}

func (x *ListCurrenciesResponse) GetCurrencies() []*CurrencyProto {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetRatesRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	AsOf          string                 `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"` // RFC3339
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`             // ISO date alias for backward compat
	Stale         bool                   `protobuf:"varint,4,opt,name=stale,proto3" json:"stale,omitempty"`
	Rates         map[string]float64     `protobuf:"bytes,5,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{4}
}

func (x *GetRatesResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetRatesResponse) GetAsOf() string {
	if x != nil {
		return x.AsOf
	}
	return ""
}

func (x *GetRatesResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetRatesResponse) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *GetRatesResponse) GetRates() map[string]float64 {
	if x != nil {
		return x.Rates
	}
	return nil
}

var File_currency_proto protoreflect.FileDescriptor

const file_currency_proto_rawDesc = "" +
	"\n" +
	"\x0ecurrency.proto\x12\bcurrency\"\x17\n" +
	"\x15ListCurrenciesRequest\"\x81\x01\n" +
	"\rCurrencyProto\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\tR\x04flag\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\x05R\bdecimals\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"Q\n" +
	"\x16ListCurrenciesResponse\x127\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x17.currency.CurrencyProtoR\n" +
	"currencies\"%\n" +
	"\x0fGetRatesRequest\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\"\xdc\x01\n" +
	"\x10GetRatesResponse\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12\x13\n" +
	"\x05as_of\x18\x02 \x01(\tR\x04asOf\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x14\n" +
	"\x05stale\x18\x04 \x01(\bR\x05stale\x12;\n" +
	"\x05rates\x18\x05 \x03(\v2%.currency.GetRatesResponse.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x012\xa9\x01\n" +
	"\x0fCurrencyService\x12S\n" +
	"\x0eListCurrencies\x12\x1f.currency.ListCurrenciesRequest\x1a .currency.ListCurrenciesResponse\x12A\n" +
	"\bGetRates\x12\x19.currency.GetRatesRequest\x1a\x1a.currency.GetRatesResponseBKZIgithub.com/zapmarket/zapmarket/services/currency-service/proto/currencypbb\x06proto3"

var (
	file_currency_proto_rawDescOnce sync.Once
	file_currency_proto_rawDescData []byte
)

func file_currency_proto_rawDescGZIP() []byte {
	file_currency_proto_rawDescOnce.Do(func() {
		file_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)))
	})
	return file_currency_proto_rawDescData
}

var file_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_currency_proto_goTypes = []any{
	(*ListCurrenciesRequest)(nil),  // 0: currency.ListCurrenciesRequest
	(*CurrencyProto)(nil),          // 1: currency.CurrencyProto
	(*ListCurrenciesResponse)(nil), // 2: currency.ListCurrenciesResponse
	(*GetRatesRequest)(nil),        // 3: currency.GetRatesRequest
	(*GetRatesResponse)(nil),       // 4: currency.GetRatesResponse
	nil,                            // 5: currency.GetRatesResponse.RatesEntry
}
var file_currency_proto_depIdxs = []int32{
	1, // 0: currency.ListCurrenciesResponse.currencies:type_name -> currency.CurrencyProto
	5, // 1: currency.GetRatesResponse.rates:type_name -> currency.GetRatesResponse.RatesEntry
	0, // 2: currency.CurrencyService.ListCurrencies:input_type -> currency.ListCurrenciesRequest
	3, // 3: currency.CurrencyService.GetRates:input_type -> currency.GetRatesRequest
	2, // 4: currency.CurrencyService.ListCurrencies:output_type -> currency.ListCurrenciesResponse
	4, // 5: currency.CurrencyService.GetRates:output_type -> currency.GetRatesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_currency_proto_init() }
func file_currency_proto_init() {
	if File_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_proto_rawDesc), len(file_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_proto_goTypes,
		DependencyIndexes: file_currency_proto_depIdxs,
		MessageInfos:      file_currency_proto_msgTypes,
	}.Build()
	File_currency_proto = out.File
	file_currency_proto_goTypes = nil
	file_currency_proto_depIdxs = nil
}
