apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: zapmarket-loki
    url: http://zapmarket-loki:3100
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
