// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: proto/product_catalog.proto

package productcatalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SellerId      string                 `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Attributes    string                 `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"` // JSON string
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductProto) Reset() {
	*x = ProductProto{}
	mi := &file_proto_product_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductProto) ProtoMessage() {}

func (x *ProductProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductProto.ProtoReflect.Descriptor instead.
func (*ProductProto) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ProductProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductProto) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductProto) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ProductProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductProto) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductProto) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *ProductProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SKUProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode       string                 `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	VariantAttrs  string                 `protobuf:"bytes,4,opt,name=variant_attrs,json=variantAttrs,proto3" json:"variant_attrs,omitempty"` // JSON string
	PriceAmount   int64                  `protobuf:"varint,5,opt,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	ComparePrice  int64                  `protobuf:"varint,6,opt,name=compare_price,json=comparePrice,proto3" json:"compare_price,omitempty"` // 0 means not set
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	WeightGrams   int32                  `protobuf:"varint,8,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"` // 0 means not set
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKUProto) Reset() {
	*x = SKUProto{}
	mi := &file_proto_product_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKUProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKUProto) ProtoMessage() {}

func (x *SKUProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKUProto.ProtoReflect.Descriptor instead.
func (*SKUProto) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *SKUProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SKUProto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SKUProto) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *SKUProto) GetVariantAttrs() string {
	if x != nil {
		return x.VariantAttrs
	}
	return ""
}

func (x *SKUProto) GetPriceAmount() int64 {
	if x != nil {
		return x.PriceAmount
	}
	return 0
}

func (x *SKUProto) GetComparePrice() int64 {
	if x != nil {
		return x.ComparePrice
	}
	return 0
}

func (x *SKUProto) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SKUProto) GetWeightGrams() int32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

func (x *SKUProto) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SKUProto) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SKUProto) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductProto          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_product_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductResponse) GetProduct() *ProductProto {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetProductResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetSKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKURequest) Reset() {
	*x = GetSKURequest{}
	mi := &file_proto_product_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKURequest) ProtoMessage() {}

func (x *GetSKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKURequest.ProtoReflect.Descriptor instead.
func (*GetSKURequest) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetSKURequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

type GetSKUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SKUProto              `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKUResponse) Reset() {
	*x = GetSKUResponse{}
	mi := &file_proto_product_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKUResponse) ProtoMessage() {}

func (x *GetSKUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKUResponse.ProtoReflect.Descriptor instead.
func (*GetSKUResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetSKUResponse) GetSku() *SKUProto {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *GetSKUResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetSKUsByProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"` // if true, returns only is_active=true SKUs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKUsByProductRequest) Reset() {
	*x = GetSKUsByProductRequest{}
	mi := &file_proto_product_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKUsByProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKUsByProductRequest) ProtoMessage() {}

func (x *GetSKUsByProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKUsByProductRequest.ProtoReflect.Descriptor instead.
func (*GetSKUsByProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetSKUsByProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetSKUsByProductRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type GetSKUsByProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []*SKUProto            `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKUsByProductResponse) Reset() {
	*x = GetSKUsByProductResponse{}
	mi := &file_proto_product_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKUsByProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKUsByProductResponse) ProtoMessage() {}

func (x *GetSKUsByProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKUsByProductResponse.ProtoReflect.Descriptor instead.
func (*GetSKUsByProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetSKUsByProductResponse) GetSkus() []*SKUProto {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *GetSKUsByProductResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_product_catalog_proto protoreflect.FileDescriptor

const file_proto_product_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product_catalog.proto\x12\x0fproduct_catalog\"\x9c\x02\n" +
	"\fProductProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\tR\bsellerId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"attributes\x18\a \x01(\tR\n" +
	"attributes\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xdb\x02\n" +
	"\bSKUProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x19\n" +
	"\bsku_code\x18\x03 \x01(\tR\askuCode\x12#\n" +
	"\rvariant_attrs\x18\x04 \x01(\tR\fvariantAttrs\x12!\n" +
	"\fprice_amount\x18\x05 \x01(\x03R\vpriceAmount\x12#\n" +
	"\rcompare_price\x18\x06 \x01(\x03R\fcomparePrice\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12!\n" +
	"\fweight_grams\x18\b \x01(\x05R\vweightGrams\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"r\n" +
	"\x12GetProductResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.product_catalog.ProductProtoR\aproduct\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"&\n" +
	"\rGetSKURequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\"b\n" +
	"\x0eGetSKUResponse\x12+\n" +
	"\x03sku\x18\x01 \x01(\v2\x19.product_catalog.SKUProtoR\x03sku\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"Y\n" +
	"\x17GetSKUsByProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"n\n" +
	"\x18GetSKUsByProductResponse\x12-\n" +
	"\x04skus\x18\x01 \x03(\v2\x19.product_catalog.SKUProtoR\x04skus\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xa2\x02\n" +
	"\x15ProductCatalogService\x12U\n" +
	"\n" +
	"GetProduct\x12\".product_catalog.GetProductRequest\x1a#.product_catalog.GetProductResponse\x12I\n" +
	"\x06GetSKU\x12\x1e.product_catalog.GetSKURequest\x1a\x1f.product_catalog.GetSKUResponse\x12g\n" +
	"\x10GetSKUsByProduct\x12(.product_catalog.GetSKUsByProductRequest\x1a).product_catalog.GetSKUsByProductResponseB\x14Z\x12./productcatalogpbb\x06proto3"

var (
	file_proto_product_catalog_proto_rawDescOnce sync.Once
	file_proto_product_catalog_proto_rawDescData []byte
)

func file_proto_product_catalog_proto_rawDescGZIP() []byte {
	file_proto_product_catalog_proto_rawDescOnce.Do(func() {
		file_proto_product_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_catalog_proto_rawDesc), len(file_proto_product_catalog_proto_rawDesc)))
	})
	return file_proto_product_catalog_proto_rawDescData
}

var file_proto_product_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_product_catalog_proto_goTypes = []any{
	(*ProductProto)(nil),             // 0: product_catalog.ProductProto
	(*SKUProto)(nil),                 // 1: product_catalog.SKUProto
	(*GetProductRequest)(nil),        // 2: product_catalog.GetProductRequest
	(*GetProductResponse)(nil),       // 3: product_catalog.GetProductResponse
	(*GetSKURequest)(nil),            // 4: product_catalog.GetSKURequest
	(*GetSKUResponse)(nil),           // 5: product_catalog.GetSKUResponse
	(*GetSKUsByProductRequest)(nil),  // 6: product_catalog.GetSKUsByProductRequest
	(*GetSKUsByProductResponse)(nil), // 7: product_catalog.GetSKUsByProductResponse
}
var file_proto_product_catalog_proto_depIdxs = []int32{
	0, // 0: product_catalog.GetProductResponse.product:type_name -> product_catalog.ProductProto
	1, // 1: product_catalog.GetSKUResponse.sku:type_name -> product_catalog.SKUProto
	1, // 2: product_catalog.GetSKUsByProductResponse.skus:type_name -> product_catalog.SKUProto
	2, // 3: product_catalog.ProductCatalogService.GetProduct:input_type -> product_catalog.GetProductRequest
	4, // 4: product_catalog.ProductCatalogService.GetSKU:input_type -> product_catalog.GetSKURequest
	6, // 5: product_catalog.ProductCatalogService.GetSKUsByProduct:input_type -> product_catalog.GetSKUsByProductRequest
	3, // 6: product_catalog.ProductCatalogService.GetProduct:output_type -> product_catalog.GetProductResponse
	5, // 7: product_catalog.ProductCatalogService.GetSKU:output_type -> product_catalog.GetSKUResponse
	7, // 8: product_catalog.ProductCatalogService.GetSKUsByProduct:output_type -> product_catalog.GetSKUsByProductResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_product_catalog_proto_init() }
func file_proto_product_catalog_proto_init() {
	if File_proto_product_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_catalog_proto_rawDesc), len(file_proto_product_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_catalog_proto_goTypes,
		DependencyIndexes: file_proto_product_catalog_proto_depIdxs,
		MessageInfos:      file_proto_product_catalog_proto_msgTypes,
	}.Build()
	File_proto_product_catalog_proto = out.File
	file_proto_product_catalog_proto_goTypes = nil
	file_proto_product_catalog_proto_depIdxs = nil
}
